project:
  name: biofuel-enose-gcn-lstm
  version: 1.0.0
  description: Sistema Bio-E-Nose con Inteligencia Artificial para Control de Calidad de Biocombustibles

authors:
  - The-Yuu7

stack:
  frontend: auto
  backend: auto
  python: auto

database:
  engine: auto

deployment:
  docker: auto

quality:
  sonar: true

security:
  trivy: true
