# SonarQube / SonarCloud Root Configuration File
# Project Identification
sonar.projectKey=The-Yuu7_NoseIA
sonar.organization=the-yuu7
sonar.projectName=NoseIA
sonar.projectVersion=1.0.0

# Source Directories to Analyze
sonar.sources=backend,python,infrastructure,database

# Exclusions: Ignore third-party vendor libraries, compiled binaries, duplicates, and datasets
sonar.exclusions=**/static/tailwind.js, **/static/chart.js, **/*.csv, **/*.tflite, **/*.pkl, **/modelo_exportado/**, frontend/**

# Test Files & Coverage Integration
sonar.tests=backend/test_api.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
